adguard-home: 
  
  env:
    TZ: "Europe/Rome"
    
  persistence:
    config:
      enabled: true
      mountPath: /opt/adguardhome/conf
      accessMode: ReadWriteOnce
    data:
      enabled: true
      mountPath: /opt/adguardhome/work
      accessMode: ReadWriteOnce

