adguard-home: 
  service:
    annotations:
      metallb.universe.tf/address-pool: adguard
      metallb.universe.tf/allow-shared-ip: adguard
    type: LoadBalander
  
  env:
    TZ: "Europe/Rome"
    
  persistence:
    config:
      enabled: true
      mountPath: /opt/adguardhome/conf
      accessMode: ReadWriteOnce
      size: 200Mi
    data:
      enabled: true
      mountPath: /opt/adguardhome/work
      accessMode: ReadWriteOnce
      size: 1Gi

