metallb:
  configInline:
    address-pools:
    - name: k8s-ip-space
      protocol: layer2
      addresses:
      - 172.24.1.15-172.24.1.20
    - name: traefik
      protocol: layer2
      addresses:
        - 172.24.1.11

