apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-lcisp-it-staging
  namespace: cert-manager
spec:
  secretName: home-lcisp-it-staging-secret
  privateKey:
    rotationPolicy: Always
  dnsNames:
  - home.lcisp.it
  #- <app.mydomain.com>
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io