apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCKRuYP/T9a3M8B5lYgoSs6A1oTx7VIwAvVPK6SJMqF+L4Lq8eng5Lw0tf2OPD7b0FuRRkl6XeZ+JrWUY1PYUmP6GISKurekncKWsNuitv3j+lNBFLjlLNn8/7FsxmzEniJ0GuNg8Yf2mrTHXLSjZQhb1Z4U5yXzV/iQAo2grOcvg76kcbWLPsq2xXjp4/V9BCdA8HbjU+KM4SDuNWuFVm/jMzTrvP3E761sPDH6wYxw7OuvuIm6z49wMejLP/fK3RXb9hZR+RErsXpbqUyWRSVcksIGy8PMdKNZtGrYtHCI0wyPwsfLOKGi/rrwa8I1q9G+zRS+jairbq+9Hx159isteBl6YRAdG5BQ13yoYNPi8lYOI5yZPsF1k5Upu56rhBVaBJCnMi0HeAD2TguPxt2PfPv5FB9MYiyyrwYq+rhm8ggsjNURLg2Sh1HkfWixe1M5ivHuiB/hveg9KSYSKVLG0KleSvaFEEThl12d6zINq9P8H+SLRnlLR3sNP0IWNES3JFlCu7MmU/2bUTk6/yWQ0fM66W9c774NbFJb2Ig3cX+HnaPXeHUOnMcIcZ0pC8hATm4MDAhJ4tif8WTp25tiO0dwI7U0V6Zul/t4KQEuYRQ7dik7MAjUaziYym+X5HqvAjTTfsszhZDDTmCGdkLu+ZmTD7qhc5sfqHklBwUlnGpfxi7FhCns5g3gUVXWPpmIbOGmb+K1Ni9nVOI3c/jvO+eTQqPunLjMVVRTg0zWScq0lIS2lY4
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: default
    type: Opaque

