apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAw638wXMhAzm/SMWlZBH5gxUuH3+8bSyZe8lf0NXE9L8NKwgYdM3+g4gGrBQm9zvMe0XiRyawxmMqJO7/4QVu4Ky+976rDEXJaL6Y/75hYNHAuw8ZXGpDwcnTzwKjr7GZmitRf4xUMGdhb5gDHinDj5Sber+0V2/JcIvQTPoYhuY9lns30XW5vsPZ1r3tRxcXbxicBGPnwS6t+EC087IA7tNVOSeRloOvkHRtCqIy7bcFsvC8mqf+e6R3R1g7RGz57CdFaMxLY4hV3PpuyBXvy5iZjzgV54cuvv3uP49mROyTLEBzz07rkSpvthMnn5bNOyGrrhHWudByb0T088UZw4k0Y946eUgL+g1mlgh3F+AyqYnfXZ5k1keMWwIS8M4Ef82TtlzUL/9/SL4RPhS5T2PPZ4NoPp6Ih8WF80yQxGtRyLdZ+OxBcv5YIrV9RVsbZJnkcMdlPvyGUQDi2GnbdRWkGHrKgptXtItdH0vR8IQYDYRgsu1tRMS9koiMazCD9TbJNW/jQY33Y7sGEd8VzSmOLTB0bUpAfI7cm8K9LjEZ7KsOotIofJylq8hP6Xlgk5lVdvd9cIMYnFx9pRhCI2enPW1VQNNZNUYwXhAvOcqKY6YL5JCEuHsc26YNb1ar6+vRIU12bfvsnmXfF8rjkD/kztqHcnnwDf1Lc3GiQr/FQlMA4Bq2LjRgG992RJG/2SKqfrZ4krXejw+icl6avb0ElVnZyvBII9yN0hSB8hZbRpfg2ngEQ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque

