apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-credentials
  namespace: traefik
spec:
  encryptedData:
    apiKey: AgCoK9wxW9Cwf3PYmAtGzqnE7O74G9+tZDxDy+i3clOGUYbj7bYWjY3szkCeCNSgUv2awxt69BI5OLMzgIj0qaKXUhgQL7wxGP5FTEqobuBt1pBu1cmbpETp3DoS/k6dOjNZKDo6jXmkRr8tAQiLe88uj6niZz1ob5OcBn0ZZTMsk65kpSfXQeS1/Srxr6sTxQ4xgS3zVT1WyUOb5vL3U2upu2y7DeH0HiL1rlY9cbcR54qwW6RVx1huj7JL89/lZ+JR4lsX+0+MYMEDDoFfpiQxv2FOsTEJNH++9Bs2Va5gRGPjvclv5avUsNo7ex5J8Ag7Sk90Ay6IYs19ADAJhLnSH9mip2DIm0D+hkrbwzUYy3meAcdBCVuiq8sZ30uxMB0gHdkJGzHwWU59tH2ZLRlte/Qo/3YXfIjwleeTmoGA/TEkajdD5RapkZIBBeMd6oPK9X/8LBy8nKEpqry36uycUXt8ldEZGd/Jbocm+boCdT7jVdWPCp6QRe1RjMYaownBvsFsUrGw91QJBS68nWuX6uIiHnfJuLqQRO7QmNWYCkkY7sqYeRaJfuFRLz+yZwsnU52NOGL3qVD83ODQzshBFJIZUQqb/MXnpDkB4zZmD0Ap0x6HEUznaggOdsE9Zf0z6hL85cyKMFiI0RKppSz4BcVKykxlosNrNeFESRXKuGvLhtenKhFXhEjz0oiYyZa3Dp5hYpPI9LfVSjSfwq6YCaSk8vxX23GBbh1MKzE5Yl8G4fDS
    email: AgAF5+bMDEpcGuPSeevKACcECz+wwvLd6aTARhJ4qlE3YcgN+BZZHjtxEPw6bCVuhkOPWs6gJHEasQXBz911bv2ZGWzKalf7yOwyBJlYBbkQKOLDEaCNi1pxKO/zgj9n4n1eQOKCe1e3aEJ5nkGkF/VTqZy/KfoQCXJBlPQkhYi+Mpn+MaJvk3vMAckY586WPBSlFhXRv+U6SHiK956wuSBJoqYTevO6Ha8oNd18pJHFhciSmQyKuIJRGPFQBm0rFYyztOr8BR351bD+KrVLqBIBvogX0gYZMK947r8XQxCRWdHeF8eTmIctuxOQHMse8TnsYpsVrQDyGkmzmX5IDZm5TyZWWGXRvykJ1DiuJn8LN0ttmW9Q0O6w2u7cb2kexAGfvfsDn0R8ADsEIx8qt4gcVk4NnU7k3Y+UloVv+WjiI9pIpdEmw4cOSSEPhG3EzdnBW676bJYOaeUjyCccAB2rXSyfc5Mk0TYdeql614vqab5WMUTARv/Ayn6ixhXnH/9CA2SNWIb7T4ev1QMrqSDtODYsXqNKVxzVzu/lF7qUerc+AwCgUq7Ua91cdUN2FOUu11VyDDm6ckrhS/k3OdevNN2F1bRj7Gy2bpZIYxlhMrEPXlt1ujwTCTvlx9khM+iKorhAqNlXVJ2AKYS4GrC8COddXQuEvgWG49NIozVbZHk/W540gjN/Ic1HvNwcIVX0DRuQ3znRHP8W5WA34d1TpjTn8Ay9OUCt
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-credentials
      namespace: traefik
    type: Opaque

