apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-credentials
  namespace: traefik
spec:
  encryptedData:
    apiKey: AgCNXAp86nsfAuAJJ17I3kAiI6LQubWA+s30csmofWRquNeHPbYwb/i06Kuv9EzreTuerAIkX1DeczFEGlrTAPYw+qJGykxNULONe4otfQw6cAKshG3a7kHDHQWoE2CH2/++25xELSr6I6D8yn8xy81mHaSoakBsN0621QUPD0pqN9d5BOc/PogtkWWkJuJuryvZY0UvJVf/tulrzj85z05MIrkHd6PtAacaurMINK/buslQTj7HQassBBsTjpGSDO8LeJT7IMJE68ZjdPFTr27kTwESrVDtSsR5oOwCvfhsGBBQ8mKWcI+6MRnU3BT/1N8jWVDTUU3QjsFPHkDFjJHggrVfVjbM8kQY7h3yVwiRdTAMTjJpqSrNoIMpsEOJmBsW0zrwM+NmsHWO1CDwEN6dUKOrMoPrGZ8StNhslIB7qLSxo5bygBtXIiOKfq0NcKZnviNKiyAXHcW2umAEJXWSKf0kjSYpAT9c5L/6zWZ84X3mrviFqMTkZA6YCmd9Os+vjtJpxccLzOAikzey/mTRzA9wQjwKMWUy9byKPQ7qMa8JCCLZv2pqmQ50cpJt8et8aC65CuzoJEK2tFyuN9kbuVrC461f2o9QHIxNWiONtKR2WBDn022dS/RSiKktN9aGKeWAoxgvLwsyac1U4npmFnygZ0to2XYYVEyEPlDGUzdZQslfUf893JXbOy75f2eFm7CTbn8JiXEpnO4qbaRcfuBrXzqF/k1T840SqH5n89E4ZRJe
    email: AgBeLFyL0eneUqVyOqxduBI7ccdz4oY6gRZXRg5w2jIpHtpYWLI7OxBVP7bIfzIDM1tU5iny8UvIg6a56UdByDrCd3ZceFvkZBGvZc3jgnqvG7lJmJoLoo+B6TPiZiaE5iYKFmdWf1AvGYpZOMkjZQAkbKoSedOkvWf1qhxFWPwOSGYc/sBCxf5O1glDRVaVwuj318DNL302tFaPHHrMnQn/+O3WypKUs04fevJIG2WxNbIvCjs8dD6lk6jLFc5rLSlIougkmqqEUDc6vLPe7wBnQLsB/NFZTX3uvdgGeWHyE51x8w3GWG80J1njf3zUDdAY3m/ShwwGLL82pLdQ3UYunxgkQAZVER7VSBXiWOnq6EY30UdIbe+KBUwjXbt83yWEqFwXmCbthKquuaKlbkg4lY+YYLgnMnNdszva6wRhHZmOTJF7xM5bSrK4KJy3W6jlnwo1Jdv8I482yxb9ax0usXH5YBn6TRejrQ3ov/OgibGsz7PoOTGH4EUME+1wCOjY3dglTNZ/eml6WYit2vZEwQNhEXy6F2YDKwie843/uydEabWuiH/KezhrnLwE/KxTCXgSIbygMrUpzs83PHA4JJw9va9GwYWIwcnYoB42bvjnfCHyFP0jzgU1HvLZi84x61O8yhl4YMOQ0oA2d5oW2c7XuhA5H4za80Ewc/SisWYp6Ji3JP13RJdDXVKJnTS1xsOOhS5M/sR7r1//HKyZ+8bjYVa4q7SH
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-credentials
      namespace: traefik
    type: Opaque

