apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-credentials
  namespace: traefik
spec:
  encryptedData:
    apiKey: AgCaAlmCRRsZbk6sy/dxsyXl6kh/BxwUmvMmvE2GVTr5gYZsTu0VaZXMfXbrTEjYBW0eUVlJSAjDOEmrA61QN39RhE7xhU/avFkS/97rYXgYhyIHY9qKiTcEEs5hP6PSbfN9BgCvit54gmMo/h5fUqv5juTIhj15+oaGnqSdrwUsk5LE3vxdTOEPBvFZMpHFgBVrLviVRIQn/kW8pZjEp06QxwAgpqwa9vtQdYsqiYoi37JIFRHQrnAZLV1/lObucTBBHn3kKIi4CwtDkTCQbXDRX4ZKF4ftYIxiopFuatd9B4sescus+q4u92B8APAUA953vo7zwVDSDKRMsU+/o2Yh+fNYCDBbEJTl2+1/Qsm4XhpQzX2cC9tcZOCYw1yvPO2aCzcYBzp1zwPJ/zy0LmOVuD1NoqknyDVIGX34QM6fV6EAPOf/oTng8ufb002QmmJe9k3EKQRiHtfTJOds7zMB2w8emmqfJDufqK8xothdtnqG5h5kBQzPoT+WKNHoDJ4XC/gb84h5ie+m+quLpa2xj3ppGJjkwFnhKCALtYfyUy23ph6eQEOnGjlS8ALYVr0+5ieiv/IJpHMGxs3x0dRlJZ3yRdh6KDwPNMVNNos4hmgGuW7NPkWHZWUClDiwj5PYQ2wOJYCVThjgKw476n9Z/MEY1BajEv98S6aXOPPtiAUnfs3YOUwwjM3qUIYsRRpHlCdE68tMsD6/9Od4lNJ0np7lbeKYqNXOwCTf6bFwL1OqwMHY
    email: AgColYK7FAAktMZNYU9IJvNl55Q5s6KnZHDEG8IhcjThsamsBYCW/QgikAvqgzIZncsvvdiA81C+rw4Xi84+Z0ZBGeUGrXeCbUpIPYwFWm2hdfqyWmtohzYVa91PxEWz0VhvOniMVVa4SS1zB7IGphW2tCvqGsZgn447pJcKzark8GKn2p0GSpC3LpdUQuK+h2VDt+pgMQ/2PvVy4SCItRzejsGaAOQw+SwHPQH8cKk3qesCwkvbrsv9JrHk8Vg5n/sKpAm3Ir7AanQ11ug3FJJuBLpw+oxU/bqkSaZqOZjmPXRr/pJDyVwprkXMGwRHO2vlgLLNzdWuzZ9BA5ReDfkGqbi6BveVAHE8KRoBQdcUzzFEvDN7bX+Kb+cOsgSGS5Jcv+hOq52412Kj3lZYu1MNNfQPaHtkWYgarjAt2p4AOsgDFmSMN83W2TAejnXBF8FRoJInfJVVYxRogJ0RKNtxhDlinie0gosB+NlY+H2q09AhLwTaP/U7Dwjq8vkhXFhk6Cule2J+vG5V9LfThYUJMnwgXzfpwuSotBDn7KTHT41jVuNbFP5kbatwZCvDA8SP5Y7JrSJ6gGV+MZscwa4AP5/lMO3ROuoZ9/0adNILcA+1E8cTcAc+6Uw73gPnmQcj+soMoZZQG3THRCR+l6Leewu6+JKmyNOQpYARrQdpzCvoN5hNt7gYiNk9zFHavtXkarOhy7cEBUS1RfUS4Vrul/alU8EqgeEp
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-credentials
      namespace: traefik
    type: Opaque

