pod-gateway:
  env:
    TZ: "Europe/Rome"
    USER_ID: 1000
    GROUP_ID: 1000
  routed_namespaces:
  - routed-vpn
  settings:
    NOT_ROUTED_TO_GATEWAY_CIDRS: "172.24.1.0/24 172.22.0.0/16 172.24.0.0/16 10.244.0.0/16"