spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/lucacalcaterra/k0s-home
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
