qbittorrent:
  persistence:
    media:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
      mountPath: /media
    downloads:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
      mountPath: /downloads
    # per comunicare vpn e qbt quando vpn pronta
    config:
      enabled: true
      # type: emptyDir
      # mountPath: /config
      # accessMode: ReadWriteOnce
      # size: 1Gi
      # mountPath: /qBittorrent
    shared:
      enabled: true
      type: emptyDir
      mountPath: /shared

  addons:
    vpn:
      enabled: true
      # You might use `openvpn` or `wireguard`
      type: openvpn
      openvpn:
      # VPN settings stored in secret `vpnConfig`. The secret mus have a key
      # a key called `vpnConfigfile` with the openvpn/wireguard config files in them
      configFileSecret: qbittorrent-vpn-config
  scripts:
    up: |-
      #!/bin/bash
      /etc/openvpn/up.sh
      echo "connected" > /shared/vpnstatus

    down: |-
      #!/bin/bash
      /etc/openvpn/down.sh
      echo "disconnected" > /shared/vpnstatus
